apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  type: NodePort
  selector:
    app: nextjs
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: quino28/ssinfo
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: app-src
              mountPath: /ssinfo/app
            - name: prisma-src
              mountPath: /ssinfo/prisma
            - name: tailwind-config
              mountPath: /ssinfo/tailwind.config.ts
            - name: next-config
              mountPath: /ssinfo/next.config.ts
            - name: pkg-json
              mountPath: /ssinfo/package.json
            - name: yarn-lock
              mountPath: /ssinfo/yarn.lock
          command: ["yarn", "dev"]
      volumes:
        - name: app-src
          hostPath:
            path: /ssinfo/app
            type: Directory
        - name: prisma-src
          hostPath:
            path: /ssinfo/prisma
            type: Directory
        - name: tailwind-config
          hostPath:
            path: /ssinfo/tailwind.config.ts
            type: File
        - name: next-config
          hostPath:
            path: /ssinfo/next.config.ts
            type: File
        - name: pkg-json
          hostPath:
            path: /ssinfo/package.json
            type: File
        - name: yarn-lock
          hostPath:
            path: /ssinfo/yarn.lock
            type: File
